title: Data Science Laboratory
email: a.r.manashty@gmail.com

description: >-
  Data Science Library

baseurl: ""
url    : "http://urdatascience.ca"


plugins:
  - jekyll-feed


analytics:
  google: G-FNP1NFTNBB


markdown: kramdown
permalink: pretty


collections:
  blog:
    output: true
  news:
    output: true
  projects:
    output: true
  members:
    output: true
