version: "3.8"

services:
  jekyll:
    image: jekyll/jekyll:pages
    command: jekyll serve --watch --force_polling --verbose --incremental
    ports:
      - 4000:4000
    volumes:
      - .:/srv/jekyll
